---
title: "Homework 1"
author: "Cong Zhang"
date: 2020-09-19
output: github_document
---

This is my solution to Homework 1.

```{r message = FALSE}
library(tidyverse)
```


## Problem 1

Create a data frame with the required elements.

```{r create_df}
prob1_df = 
  tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("low", "low", "low", "mod", "mod", "mod", "mod", "high", "high", "high"))
  )
```

Take the mean of each variable in my data frame.

```{r mean_pull_var}
mean(pull(prob1_df, samp))
mean(pull(prob1_df, samp_gt_0))
mean(pull(prob1_df, char_vec))
mean(pull(prob1_df, factor_vec))
```

I can take the mean of numbers and logical but not character or factor. 

```{r try_numeric, eval = FALSE}
as.numeric(pull(prob1_df, samp))
as.numeric(pull(prob1_df, samp_gt_0))
as.numeric(pull(prob1_df, char_vec))
as.numeric(pull(prob1_df, factor_vec))
```

```{r}
as.numeric(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
as.factor(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
as.numeric(as.factor(pull(prob1_df, samp_gt_0))) * pull(prob1_df, samp)
```



